name: movies_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  provider: ^6.1.2
  fast_immutable_collections: ^10.2.4
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.6
  state_notifier: ^1.0.0
  flutter_state_notifier: ^1.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  loading_animation_widget: ^1.3.0
  get_it: ^8.0.0
  youtube_explode_dart: ^2.2.2
  video_player: ^2.9.1
  chewie: ^1.8.5
  font_awesome_flutter: ^10.8.0
  equatable: ^2.0.7
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  path_provider: ^2.1.5
  dartz: ^0.10.1
  carousel_slider: ^5.0.0
  animate_do: ^4.2.0
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.4.5
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0



flutter:


  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/icons/
